INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Главная', 'FOLDER', 0, NULL, 'desc1',1); --главная
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('файл1', 'FILE',1, '/resources/images/profile.jpg', 'desc2',1);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('ПОДГОТОВКА К ЦТ/ЦЭ', 'FOLDER',0, NULL, NULL, 2);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Книги для подготовки к ЦТ', 'FOLDER',3, NULL, NULL ,1);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Темы', 'FOLDER',3, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Рациональные уравнения', 'FOLDER',5, NULL, NULL ,1);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Иррациональные уравнения', 'FOLDER',5, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Тригонометрия', 'FOLDER',5, NULL, NULL ,3);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Разбор заданий с ЦТ и ЦЭ', 'FOLDER',3, NULL, NULL ,3);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2003 год', 'FOLDER',9, NULL, NULL ,1);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2004 год', 'FOLDER',9, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2005 год', 'FOLDER',9, NULL, NULL ,3);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2006 год', 'FOLDER',9, NULL, NULL ,4);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2007 год', 'FOLDER',9, NULL, NULL ,5);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2008 год', 'FOLDER',9, NULL, NULL ,6);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2009 год', 'FOLDER',9, NULL, NULL ,7);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2010 год', 'FOLDER',9, NULL, NULL ,8);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2011 год', 'FOLDER',9, NULL, NULL ,9);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2012 год', 'FOLDER',9, NULL, NULL ,10);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2013 год', 'FOLDER',9, NULL, NULL ,11);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2014 год', 'FOLDER',9, NULL, NULL ,12);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2015 год', 'FOLDER',9, NULL, NULL ,13);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2016 год', 'FOLDER',9, NULL, NULL ,14);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2017 год', 'FOLDER',9, NULL, NULL ,15);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2018 год', 'FOLDER',9, NULL, NULL ,16);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2019 год', 'FOLDER',9, NULL, NULL ,17);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2020 год', 'FOLDER',9, NULL, NULL ,18);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2021 год', 'FOLDER',9, NULL, NULL ,19);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2022 год', 'FOLDER',9, NULL, NULL ,20);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2023 год', 'FOLDER',9, NULL, NULL ,21);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('2024 год', 'FOLDER',9, NULL, NULL ,22);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Олимпиады', 'FOLDER',0, NULL, NULL ,4);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Журнал "Квант"', 'FOLDER',32, NULL, NULL ,1);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Тексты олимпиад', 'FOLDER',32, NULL, NULL ,2);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Первый этап', 'FOLDER',34, NULL, NULL ,1);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Второй этап', 'FOLDER',34, NULL, NULL ,2);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Третий этап', 'FOLDER',34, NULL, NULL ,3);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Республиканская', 'FOLDER',34, NULL, NULL ,4);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Темы', 'FOLDER',32, NULL, NULL ,3);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Школьная математика', 'FOLDER',0, NULL, NULL ,3);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('5 класс', 'FOLDER',40, NULL, NULL ,1);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',41, NULL, NULL ,1);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',41, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('6 класс', 'FOLDER',40, NULL, NULL ,2);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',44, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',44, NULL, NULL ,2);
           -- INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('file.xls', 'FILE',46, '/resources/files/1.xls', 'sss' ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('7 класс', 'FOLDER',40, NULL, NULL ,3);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',47, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',47, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('8 класс', 'FOLDER',40, NULL, NULL ,4);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',50, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',50, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('9 класс', 'FOLDER',40, NULL, NULL ,5);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',53, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',53, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('10 класс', 'FOLDER',40, NULL, NULL ,6);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',56, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',56, NULL, NULL ,2);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('11 класс', 'FOLDER',40, NULL, NULL ,7);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Учебники', 'FOLDER',59, NULL, NULL ,1);
            INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Отдельные темы', 'FOLDER',59, NULL, NULL ,2);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Обо мне', 'FOLDER',0, NULL, NULL ,6);
INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('ЭОР', 'FOLDER',0, NULL, NULL ,5);
    INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Канал "Геометрия Валерий Казаков"', 'FOLDER',63, NULL, NULL ,1);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('GDZ VIDEO', 'LINK',64, 'https://www.youtube.com/@gdzvideo5339', 'YouTube канал' ,1);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('GDZ VIDEO', 'LINK',64, 'https://www.youtube.com/embed/mJu_RBp3Qic?si=xzl7b8JY7age1Vpo', '№ 1-100 - Геометрия 8 класс Казаков' ,2);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('GDZ VIDEO', 'LINK',64, 'https://www.youtube.com/embed/uTvT7-Hui44?si=LLhcm-_to0G-M2sC', '№ 101-200 - Геометрия 8 класс Казаков' ,3);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Посмотреть весь плейлист', 'LINK',64, 'https://www.youtube.com/playlist?list=PLtgE87VTmyY-whbZVMWags2too_uidDet', NULL ,6);
        INSERT INTO nodes (name, type, parent_id, url, description,element_position) VALUES ('Посмотреть весь плейлист', 'LINK',64, 'https://www.youtube.com/embed/N0VqRdxF3C0?si=IWc52IokyDKxQzc5', 'ВПИСАННЫЙ КВАДРАТ. Удача с нами!' ,6);